### ISSUE TITLE
Add a loading screen image

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#22]
I have attached a loading screen we can use (that can be resized as needed).

![we_vote_loading_screen2](https://user-images.githubusercontent.com/7756031/36919586-b38ca302-1e12-11e8-984f-2a9e501f3619.png)

**Comment by SailingSteve** [comment]
Sadly there are three loading screens:
One in native iOS, which is our blue, with "We Vote"
The second is in Cordova, which is currently white with a iOS style loading indicator
Then the third, which flashes by fast, which is the "Loading We Vote..." from src/sass/components/_loading-spinner.scss

**Comment by DaleMcGrew** [comment]
The second one is the one I see for the longest. I'm hoping we can show something during that wait. Do we have the option to show an image during the Cordova load?

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve, this is working well. For future reference, when we want to update this art, what art assets will we need to update? (i.e., what are the path and filenames in the repo?)

**Comment by SailingSteve** [comment]
@DaleMcGrew 
In order to handle the 12" iPad Pro I took your image into Photoshop, resized it to 2732x2732, forced it to have no transparent pixels, and renamed it to the required(?) name `Default@2x~universal~anyany.png`.  Then (not being an Xcode expert), I dropped the image **within the Xcode program** into
`WeVoteCordova/Resources//Images.xcassets/LaunchImage` into each location in the universal section.

<img width="1569" alt="screen shot 2018-03-23 at 8 44 35 am" src="https://user-images.githubusercontent.com/6923653/37838985-931e356c-2e76-11e8-8473-a1c18b31d87d.png">

This resulted in these files being created:

```
(WebAppEnv)Steves-MacBook-Pro-2017:ios stevepodell$ ls -la ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/*
-rw-r--r--  1 stevepodell  staff    3765 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Contents.json
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-1.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-10.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-11.png
-rw-r--r--@ 1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-2.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-3.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-4.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-5.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-6.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-7.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-8.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:27 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany-9.png
-rw-r--r--  1 stevepodell  staff  134330 Mar 22 08:26 ./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany.png
(WebAppEnv)Steves-MacBook-Pro-2017:ios stevepodell$ 
```

So to replace the splash screen, I would take `./WeVoteCordova/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany.png` and replace it with same sized art, and if you wanted to  be safe I would use Xcode to copy them (and automatically rename them) over the existing files, if you were feeling adventurous you could go directly to the files, and take the new image and use it to replace the original and the 12 numbered copies of the old image.

By the way there are many vestigial images in the xcode dir that I have no idea if they are needed or not, but messing up xcode (which stores too much configuration info in a binary file), can take days to fix, so I am leaving the old unneeded files in place.

**Comment by DaleMcGrew** [comment]
Thank you Steve! So it sounds like we should provide that one master art asset, and then follow your steps. What you wrote above would be awesome in the documentation. I really appreciate how on top of documentation you are.

**Comment by SailingSteve** [comment]
I copied it into the documentation.  It will be there on the next PR.
